Support static linking for Ruby
steveklabnik/ruby-sys pull request #20
Opened 2017-04-05 13:50 UTC by ianks

This approach essentially follows the logic outlined by @alexcrichton in
[this
issue](https://github.com/steveklabnik/ruby-sys/pull/16#issuecomment-271412827).

I have tested it on Linux against `ruru` and a few other gems, and things seem
to be working. The only hiccup I found was that we needed to specify the `LIBS`
which were used from Ruby. With the approach on #16, this was not neccesary. I
am not sure why. Does anyone have any insight to this?

Any feedback would be awesome, especially if you are a Mac user.

1. Clone ruru: `https://github.com/d-unseductable/ruru`
1. Update Cargo.toml in ruru: `ruby-sys = { git = "https://github.com/ianks/ruby-sys" }`
1. Run the tests: `RUBY_STATIC=1 cargo test`

2017-04-05 14:09 UTC, steveklabnik commented on build.rs
> +    // Cargo wants them as: `-l pthread -l gmp`
huh

2017-04-05 14:09 UTC, steveklabnik commented on build.rs
> +    // Cargo wants them as: `-l pthread -l gmp`
@alexcrichton is cargo really this strict about this? Just curious...

2017-04-05 14:10 UTC, steveklabnik requested changes

2017-04-05 14:10 UTC, steveklabnik commented on build.rs
> +    let transformed_lib_args = libs.replace("-l", "-l ")
the build is failing because there's no `;` on this line

2017-04-05 15:03 UTC, ianks commented
Updated to fix my syntax error

2017-04-05 15:05 UTC, ianks commented on build.rs
> +    // Cargo wants them as: `-l pthread -l gmp`
For reference, here is the error I get when attempting to build without spacing out the -l arg:

```
error: Only `-l` and `-L` flags are allowed in build script of `ruby-sys v0.2.20 (file:///home/ianks/Documents/FOSS/ruby-sys)`: `-lpthread -ljemalloc -lgmp -ldl -lcrypt -lm`
```

2017-04-05 15:36 UTC, steveklabnik commented on build.rs
> +    // Cargo wants them as: `-l pthread -l gmp`
TIL

2017-04-05 15:36 UTC, steveklabnik approved these changes

2017-04-05 15:37 UTC, merged

2017-04-05 15:37 UTC, steveklabnik commented
Passes now. Thank you!

2017-04-05 15:42 UTC, ianks commented
@steveklabnik did you get a chance to try it out on Mac?

2017-04-05 17:24 UTC, steveklabnik commented
I do not own a mac

2017-04-05 19:38 UTC, malept commented
We should add `os: osx` workers to the Travis config.

The main reason why I never pushed for my PR to be merged was because I haven't yet had time to test with macOS. If it doesn't work with macOS (or Windows) then we might want to limit the static check to just Linux.

2017-04-05 21:16 UTC, steveklabnik commented
Ah yes, let's do that. I haven't cut a release for this yet, so we can have some time!

2017-04-11 16:40 UTC, malept commented
FYI, I am working on this, but it's not ready for a PR yet. I only run Linux, so I am pretty much Developing Via CI Workers :tm:. Those interested can check out a certain named branch in my fork.

2017-04-30 14:51 UTC, mikeycgto commented
Trying to test this out with ruru. I changed the Cargo entry to point to ruby-sys on github. When I run `cargo test` I get the following:

```
$ cargo test
    Finished dev [unoptimized + debuginfo] target(s) in 0.15 secs
     Running target/debug/deps/ruru-5c844fb895bd6064
/home/mcoyne/Projects/ruru/target/debug/deps/ruru-5c844fb895bd6064: error while loading shared libraries: libruby.so.2.4: cannot open shared object file: No such file or directory
error: test failed
```

My Ruby is installed via rvm with `--enable-shared`. Any idea why it's not finding libruby.so or am I doing something wrong?